### ISSUE TITLE
List TLH sales within 30 days ("do not buy" list)

### ISSUE THREAD

**Issue by hoostus** [redstreet/fava_investor#33]
A wash sale can also be created by selling a lot and then, within 30 days, buying a "substantially similar" security. The "Purchases within the past 30 days creating wash sales" could be extended to also list sales that have occurred within 30 days, so users can easily see what things they should not repurchase.

**Comment by redstreet** [comment]
@hoostus : added the "best effort" feature. Try it and let me know!

Closing this. Feel free to reopen for any reason.

**Comment by hoostus** [comment]
I tried it (briefly) and it looks pretty good, especially for a "best effort". If anyone ever comes across edge cases that don't work....well, that's what patches are for :)
