### ISSUE TITLE
any fava date or account filter reverts AA to unknown

### ISSUE THREAD

**Issue by g40matt** [redstreet/fava_investor#36]
In example.bc, setting any of the default Fava filters (date, account, payee) to anything other than blank causes the AA by class report to drop the asset_allocation_* metadata and default to "unknown"

**Comment by redstreet** [comment]
Thanks for filling this.

This is a known issue: AA by class was ported in from [this](https://github.com/redstreet/beancount_asset_allocation) project and has not yet been made fava-aware. Patches welcome.
