### ISSUE TITLE
Importing module "fava_investor.fava_investor" failed.

### ISSUE THREAD

**Issue by fchtngr** [redstreet/fava_investor#48]
The readme says to include the line `2000-01-01 custom "fava-extension" "fava_investor.fava_investor" "{}"` in order to load the plugin.

However, when doing so I get an error: `Importing module "fava_investor.fava_investor" failed.`

The fix seems to be to include `2000-01-01 custom "fava-extension" "fava_investor" "{}"`. At least that worked for me. Maybe I missed something, but if the fix is correct the readme should be updated. 

Thx for the plugin, its great!

**Comment by redstreet** [comment]
@fchtngr right you are, thanks for filing this! Fixed.
