### ISSUE TITLE
Some tables don't load with 'master' fava

### ISSUE THREAD

**Issue by aclindsa** [redstreet/fava_investor#57]
If I use fava 1.18, fava_investor loads as expected. However, if I use the latest git version of fava from 'master' (I'm testing SHA 367c86ccdb73ad21a01afe8d2279f7c454adc7a8 as of this writing), some of the tables do not load. I get this instead:

![2021-04-05-073714_1334x698_scrot](https://user-images.githubusercontent.com/362852/113570190-d5ad0b80-95e1-11eb-8c21-ff2a6873a942.png)

Interestingly, both the chart and 'Portfolio: Asset Allocation by Class' on the Asset Allocation Classes view load fine, but most of the tables on the Asset Allocation Accounts, Cash Drag, and Tax Loss Harvestor views do not. There is one table in the Tax Loss Harvestor view that *does* show up - the Summary one at the top:

![2021-04-05-074024_1316x1106_scrot](https://user-images.githubusercontent.com/362852/113570571-a1861a80-95e2-11eb-9a75-776a58836e53.png)

**Comment by aclindsa** [comment]
I've skimmed through [the commit messages between fava v1.18 and master](https://github.com/beancount/fava/compare/v1.18...master) and nothing immediately sticks out at me as a potential reason for this breakage. I can attempt to `git bisect` to find where the breakage occurs if I have time in the next few days.

**Comment by aclindsa** [comment]
My `git bisect` says this is the fava commit which introduced the breakage: https://github.com/beancount/fava/commit/287fe97d104da1b72cd48dbf4c7e8458d6bf3ab2

Posting here in case you have insights to point me in the right direction. I'll keep looking into it as I have time.

**Comment by aclindsa** [comment]
Looks like they modified their `querytable` macro, breaking fava_investor's usage of it. I've made a PR, which appears to allow fava_investor to work both with the latest upstream fava and with fava 1.18: https://github.com/redstreet/fava_investor/pull/58

@redstreet Let me know how this solution looks to you.

**Comment by redstreet** [comment]
Looks great. Thanks for catching this and the PR. Merging.
