### ISSUE TITLE
Setup.py

### ISSUE THREAD

**Issue by bryall** [redstreet/fava_investor#6]
Can we get a setup.py so I can import this repo into my beancount virtual environment?

**Comment by redstreet** [comment]
I'd be happy to review a patch if you don't mind creating one. I don't use a virtual env or setup.py, so I'm not familiar with it, but it sounds like a good thing to have.

**Comment by redstreet** [comment]
I checked in a hello world example (a basic fava extension) to help.

**Comment by bryall** [comment]
Will work on a patch as soon as I get time

**Comment by redstreet** [comment]
Thank you @bryall !

**Comment by redstreet** [comment]
@bryall, the templates directory doesn't get installed as a part of the pip package. How best to fix this?

**Comment by bryall** [comment]
upon doing some research, i think we need to add a manifest.in file. I can look into this further later
