### ISSUE TITLE
Clearly indicate tabs on initial screen, and/or open with a default tab

### ISSUE THREAD

**Issue by seltzered** [redstreet/fava_investor#61]
Trying fava-investor for the first time to understand it better, using recent fava commit https://github.com/beancount/fava/commit/0f55fba031ec7228766d7474e4fc461d2163ab56 & fava-investor pr https://github.com/redstreet/fava_investor/pull/60 . Don't get any errors but everything is blank, anyone else experiencing this?

![Screen Shot 2021-06-30 at 9 16 48 PM](https://user-images.githubusercontent.com/297435/124056673-c58fa700-d9eb-11eb-9031-c72efe489092.png)

**Comment by redstreet** [comment]
Sorry, basic question: have you clicked on one of the tabs at the top?

**Comment by cataclysmic** [comment]
Had the same issue in the beginning. If possible some graphical hint that those are in fact 'tabs' would be nice. The first impression is that of headings. It might be useful to start with one tab open.

**Comment by seltzered** [comment]
On a different computer setup now but yes after clicking notice things appear. Likely didn't notice these were tab links similar to @cataclysmic was likely the problem. Thanks, closing.

**Comment by redstreet** [comment]
Completely agree, the initial UI page is confusing currently. I'm neither a UI designer nor a web programmer though, and could use some help here. Reopening this issue so it can get a fix, hopefully by a contributor.
