### ISSUE TITLE
does the module fetch prices from the web?

### ISSUE THREAD

**Issue by cataclysmic** [redstreet/fava_investor#63]
I was under the impression that this module fetches commodity prices from Google, I guess.

However, when running the module without explicit price directives in the *.beancount file it fails and I get:

'''Error: unable to convert XXX LHA to base currency EUR (Missing price directive?)
SystemExit raised: shutting down
'''

A related issue, which might be more of a question for core beancount, is the capabity of conversion across several units. Personally I denote in EUR but some stocks, fonds, etc. are denoted in USD on the web. So I would need a conversion of commodity -> USD -> EUR.

PS: I love the module. Still not sure how to configure it all but I am getting there.

**Comment by redstreet** [comment]
Hi,
You're probably looking for multi currency support. It's there in master, but not yet released. See commit a8389b4. You can do a bleeding edge install to get this, see the README.

**Comment by redstreet** [comment]
Correct, price fetching is an in depth endeavor by itself, and well outside the scope of this module. Use your favorite method to fetch and insert price entries.

**Comment by cataclysmic** [comment]
Thanks for the help.
I will do a bleedind edge install.
For price fetching a started using bean-price.

It's a great module!
