### ISSUE TITLE
Postive amounts of non-monetary commodities crash aa_class

### ISSUE THREAD

**Issue by nils-werner** [redstreet/fava_investor#64]
I have an issue with my vacation hours `VACHR` commodity and `fava_investor`: Whenever I have a positive balance of vacation hours, aa_class stops working with the message

    Error: unable to convert 15 VACHR to base currency USD (Missing price directive?)

Steps to reproduce:

 1. Remove lines [3742-3744 from `huge-example.beancount`](https://github.com/redstreet/fava_investor/blob/master/huge-example.beancount#L3742-L3744) to produce a positive balance
 2. Open `aa_class` module

I would expect fava_investor to completely ignore this commodity, as it holds no monetary value.

**Comment by redstreet** [comment]
Agreed, it should be ignored. However, there's no way aa_class can automatically infer this. Hence, this is done via configuration. Have you tried to configure the plugin, and if so, I'd be interested if you couldn't.

**Comment by redstreet** [comment]
It would be good for the example to exclude `Assets:US:Hooli:Vacation` in its configuration regex to illustrate this case. PR welcome.

**Comment by nils-werner** [comment]
Can't the plugin simply ignore commodities that don't have an asset class configured?

**Comment by redstreet** [comment]
It could, but that would risk ignoring assets where one has simply forgotten to configure the asset class. Everything seems fine, and there's no way to tell that the result being shown is incorrect.

I've run into this enough myself and decided explicit is better than implicit.

**Comment by redstreet** [comment]
Closing. Feel free to open if there are further thoughts.
