### ISSUE TITLE
Fava Investor won't load

### ISSUE THREAD

**Issue by producercoder** [redstreet/fava_investor#66]
When I click the Investor link in Fava on my beancount file I get a loading failed error. 
The relevant console output is "jinja2.exceptions.UndefinedError: 'url_for_current' is undefined"

beancount - 2.3.4
fava investor - 0.2.1
jinja2 - 3.0.3
MacOS BigSur 11.6

**Comment by redstreet** [comment]
#62 resolves this. It was due to an upstream change.

Can you please do a bleeding edge install as mentioned in the main README.md?

I'll cut a pip release soon.

**Comment by producercoder** [comment]
The bleeding edge install solved it, but I did have to go in and manually delete the fava-investor files in /usr/local/lib/python3.9/site-packages/. It may be that I installed fava-investor as su accidentally. I had to sudo rm them.

**Comment by redstreet** [comment]
Ah yes, that can always happen with pip, and should not be specific to fava-investor


Btw, I also just released a pip package from head.
