### ISSUE TITLE
Function get_account_open in favainvestorapi.py returns an empty list

### ISSUE THREAD

**Issue by jenicek** [redstreet/fava_investor#67]
With fava 1.20.1, using option `'pattern_type' = 'account_open_metadata'` in 'asset_alloc_by_account' renders an empty table in the "Asset Allocation by Accounts" tab. I've tracked the issue to the function `get_account_open` in `favainvestorapi.py` which returns an empty list. I believe the correct way is to return `self.ledger.all_entries_by_type.Open` in the function, which corrects the behaviour.

```
diff --git a/fava_investor/common/favainvestorapi.py b/fava_investor/common/favainvestorapi.py
index 28caee5..cd591d8 100644
--- a/fava_investor/common/favainvestorapi.py
+++ b/fava_investor/common/favainvestorapi.py
@@ -38,9 +38,7 @@ class FavaInvestorAPI:
         return getters.get_account_open_close(self.ledger.entries)
 
     def get_account_open(self):
-        oc = getters.get_account_open_close(self.entries)
-        opens = [e for e in oc if isinstance(e, Open)]
-        return opens
+        return self.ledger.all_entries_by_type.Open
 
     def cost_or_value(self, node, date, include_children):
         if include_children:
```

**Comment by redstreet** [comment]
Good catch. Would you like to submit your patch as a pull request? Thanks!

**Comment by jenicek** [comment]
I've already deleted the cloned repository, but it should be simple enough to just add to arbitrary commit :)

**Comment by redstreet** [comment]
While modifying a line of code is simple, getting it right isn't always so :).

Happy to look into this soon.
